# Generated by Django 4.2.24 on 2025-09-29 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, help_text='Unique identifier for the transport order', max_length=64, unique=True, verbose_name='Order Number')),
                ('date', models.DateField(db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Pickup', 'PICKUP'), ('Delivery', 'DELIVERY')], max_length=16)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='orders.order')),
            ],
        ),
        migrations.AddConstraint(
            model_name='waypoint',
            constraint=models.UniqueConstraint(fields=('order', 'location', 'type'), name='unique_waypoint_per_order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='idx_order_number'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'date'], name='idx_order_customer_date'),
        ),
    ]
